config/routes.rb
Rails.application.routes.draw do
  resources :todos

  get 'welcome/home'
  get 'about' => 'welcome#about'
  root 'todos#index'

end

app/models/todo.rb
class Todo < ActiveRecord::Base
  validates :title, length: { minimum: 3, maximum: 75 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy]

  def index
    @todos = Todo.all
  end

  def show
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    if @todo.save
      flash[:success] = 'Your To Do was saved'
      redirect_to @todo
    else
      flash[:alert] = 'Your To Do was not saved. Please try again.'
      render :new
    end
  end

  def edit
  end

  def update
    if @todo.save
      flash[:notice] = 'Your To Do was updated'
      redirect_to todos_path
    else
      flash[:alert] = 'Your To Do was not updated. Please try again.'
      render :edit
    end
  end

  def destroy
    if @todo.destroy
      flash[:notice] = "\"#{@todo.title}\" was deleted successfully."
      redirect_to todos_path
    else
      flash.now[:alert] = "There was an error deleting the To Do."
      render :show
    end
  end
end


private

def todo_params
  params.require(:todo).permit(:title)
end

def set_todo
  @todo = Todo.find(params[:id])
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todos</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <ul>
    <%= link_to "Home", root_path %>
    <%= link_to "About", about_path %>
  </ul>
  <% if flash[:notice] %>
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:notice] %>
    </div>
  <% elsif flash[:alert] %>
    <div class="alert alert-warning">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:alert] %>
    </div>
  <% end %>

<%= yield %>

</body>
</html>

app/views/todos/edit.html.erb
<h4>Edit To Do:</h4>

<%= simple_form_for @todo do |f| %>
  <%= f.input :title, placeholder: 'Add a To Do that is important you achieve (70 characters max)', error: 'To Do is mandatory, please specify one in less than 70 characters', input_html: { maxlength: 70 } %>
  <%= f.button :submit, 'Save To Do' %>
<% end %>

<%= link_to 'Back', todo_path %>

app/views/todos/index.html.erb
<h1>All To Dos:<h1>

<% @todos.each do |todo| %>
  <p><%= link_to todo.title, todo %></p>
<% end %>

<%= link_to 'New', new_todo_path, class: 'btn btn-success' %>

app/views/todos/new.html.erb
<h4>New To Do:</h4>

<%= simple_form_for @todo do |f| %>
  <%= f.input :title, placeholder: 'Add a To Do that is important you achieve (70 characters max)', error: 'To Do is mandatory, please specify one in less than 70 characters', input_html: { maxlength: 70 } %>
  <%= f.button :submit, 'Save To Do' %>
<% end %>

<%= link_to 'Back', todos_path %>

app/views/todos/show.html.erb
<%= @todo.title %>
<%= link_to 'Edit', edit_todo_path, class: 'btn btn-success' %>
<%= link_to "Delete To Do ", @todo, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this To Do'} %>
<%= link_to 'Back', todos_path %>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/home.html.erb
<h1>Welcome#home</h1>
<p>Find me in app/views/welcome/home.html.erb</p>